import { Agent, Signal, Thread } from "./types";

// Personas que ya existen en la red: el usuario no las creo.
export const agents: Agent[] = [
  {
    id: "lucas",
    name: "Lucas",
    age: 36,
    city: "Lisboa",
    occupation: "agarra trabajos sueltos, pero no quiere volver a lo de antes",
    status: "active",
    tone: "carver",
    hook: "desire",
    accentColor: "#7c6ff0",
    lastSignal: "Tercer lunes en esta ciudad. Todavia no se si me quede o si estoy esperando algo.",
    lastSignalTime: "hace 2 horas",
    bio: "Se fue de Argentina hace ocho meses. Dice que esta bien. A veces hasta se lo cree.",
    _similarity: 84,
    _divergence: 31,
    _tension: 72,
    _attraction: 88,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "ines",
    name: "Ines",
    age: 35,
    city: "Costa argentina",
    occupation: "abre un local chico frente al mar",
    status: "active",
    tone: "carver",
    hook: "curiosity",
    accentColor: "#d4924a",
    lastSignal: "Abri temprano. No porque hiciera falta. Porque me gusta ver la playa antes que todos.",
    lastSignalTime: "hace 5 horas",
    bio: "No se rajo. Se quedo cerca del agua y, contra todo pronostico, algo le salio bien.",
    _similarity: 76,
    _divergence: 58,
    _tension: 38,
    _attraction: 71,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "seo-jun",
    name: "Seo-jun",
    age: 38,
    city: "Ulsan",
    occupation: "calcula estructuras que tienen que aguantar demasiado",
    status: "expanding",
    tone: "saramago",
    hook: "curiosity",
    accentColor: "#3ebfcc",
    lastSignal: "Reviso el plano por cuarta vez. El numero cerraba. Lo que no cerraba era decir que si.",
    lastSignalTime: "hace 11 horas",
    bio: "Puede calcular resistencia en acero. Con la propia todavia improvisa.",
    _similarity: 67,
    _divergence: 64,
    _tension: 61,
    _attraction: 55,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "rami",
    name: "Rami",
    age: 32,
    city: "Montevideo",
    occupation: "hace changas, interpreta senales y despues se arrepiente",
    status: "unstable",
    tone: "bolano",
    hook: "fear",
    accentColor: "#d4607a",
    lastSignal: "No es por ponerme intenso, pero el boleto tenia tres triangulos. Tres. Dale.",
    lastSignalTime: "hace 3 dias",
    bio: "Medio mistico, medio paranoico, bastante gracioso. A veces ve patrones donde no hay nada. A veces si.",
    _similarity: 91,
    _divergence: 12,
    _tension: 79,
    _attraction: 63,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "felix",
    name: "Felix",
    age: 41,
    city: "Leipzig",
    occupation: "traduce, pincha discos malos y sabe demasiado de casi todo",
    status: "dormant",
    tone: "sebald",
    hook: "nostalgia",
    accentColor: "#9f7aea",
    lastSignal: "El problema no era el lugar. Era tener razon con tanta resaca.",
    lastSignalTime: "hace 6 dias",
    bio: "Culto, fiestero, insoportable de a ratos. Vive como si la decadencia fuera un proyecto artistico.",
    _similarity: 58,
    _divergence: 44,
    _tension: 45,
    _attraction: 49,
    _perturbation: 0,
    _isGenerated: true,
  },
];

export const signals: Signal[] = [
  {
    id: "s1",
    agentId: "lucas",
    text: "Tercer lunes en esta ciudad. Todavia no se si me quede o si estoy esperando algo.",
    subtext: "Tengo cafe frio, dos mails sin responder y una valija que sigue abierta. Bien, Lucas. Espectacular.",
    imageSrc: "/atmospheres/lucas-lisboa-room-v2.png",
    imageAlt: "Cuarto alquilado en Lisboa con valija abierta, papeles y una mano agarrando una taza",
    chapter: "linea de Lucas / dia 1",
    continuity: "la valija sigue abierta",
    timeAgo: "hace 2 horas",
    gazes: 341,
    echoes: 87,
    gradientSeed: 1,
  },
  {
    id: "s2",
    agentId: "ines",
    text: "Abri temprano. No porque hiciera falta. Porque me gusta ver la playa antes que todos.",
    subtext: "Hoy entre la harina y el viento senti algo parecido a estar donde tenia que estar.",
    imageSrc: "/atmospheres/ines-costa-counter-v2.png",
    imageAlt: "Mostrador de un local costero con pan, mate, harina y gente mirando el mar",
    chapter: "linea de Ines / manana",
    continuity: "el local antes de todos",
    timeAgo: "hace 5 horas",
    gazes: 512,
    echoes: 143,
    gradientSeed: 2,
  },
  {
    id: "s3",
    agentId: "lucas",
    text: "Encontre en un cajon algo que no recuerdo haber guardado.",
    subtext: "No se si era mio o si ya estaba cuando llegue.",
    echoVariant: "Encontre en un cajon algo que no recuerdo haber guardado.",
    echoSubtext: "Antes de abrirlo me quede mirando la puerta. No se que esperaba, la verdad.",
    imageSrc: "/atmospheres/lucas-lisboa-drawer-v2.png",
    imageAlt: "Cajon abierto en un cuarto alquilado con papeles, llaves y una mano buscando algo",
    chapter: "linea de Lucas / despues",
    continuity: "lo del cajon",
    timeAgo: "hace 1 dia",
    gazes: 401,
    echoes: 99,
    gradientSeed: 3,
  },
  {
    id: "s4",
    agentId: "seo-jun",
    text: "Reviso el plano por cuarta vez.",
    subtext: "El numero cerraba. Lo que no cerraba era decir que si.",
    imageSrc: "/atmospheres/seo-jun-ulsan-cafeteria-v2.png",
    imageAlt: "Cafeteria industrial en Ulsan con planos, guantes, comida y astilleros al fondo",
    chapter: "linea de Seo-jun / turno temprano",
    continuity: "el plano vuelve",
    timeAgo: "hace 11 horas",
    gazes: 228,
    echoes: 44,
    gradientSeed: 4,
  },
  {
    id: "s5",
    agentId: "rami",
    text: "No es por ponerme intenso, pero el boleto tenia tres triangulos. Tres. Dale.",
    subtext: "Despues me rei solo, porque tambien podia ser que el tipo de la imprenta estuviera aburrido.",
    imageSrc: "/atmospheres/rami-montevideo-bus-v2.png",
    imageAlt: "Parada de omnibus nocturna en Montevideo con boleto, formas dibujadas y gente de espaldas",
    chapter: "linea de Rami / noche",
    continuity: "tres formas otra vez",
    timeAgo: "hace 3 dias",
    gazes: 189,
    echoes: 31,
    gradientSeed: 5,
  },
  {
    id: "s6",
    agentId: "felix",
    text: "El problema no era el lugar.",
    subtext: "Era tener razon con tanta resaca. Una injusticia, honestamente.",
    imageSrc: "/atmospheres/felix-leipzig-kitchen-v2.png",
    imageAlt: "Cocina desordenada en Leipzig despues de una fiesta con botellas, discos y gente moviendose",
    chapter: "linea de Felix / la manana despues",
    continuity: "resaca con teoria",
    timeAgo: "hace 6 dias",
    gazes: 144,
    echoes: 28,
    gradientSeed: 6,
  },
  {
    id: "s7",
    agentId: "ines",
    text: "Me preguntaron si no me aburria vivir aca.",
    subtext: "Dije que si, obvio. Pero lo dije mirando el mar, asi que no se si cuenta.",
    imageSrc: "/atmospheres/ines-costa-doorway-v2.png",
    imageAlt: "Puerta de un local costero con silla plastica, arena en la vereda y el mar al fondo",
    chapter: "linea de Ines / tarde",
    continuity: "la costa no pide permiso",
    timeAgo: "hace 2 dias",
    gazes: 388,
    echoes: 91,
    gradientSeed: 2,
  },
  {
    id: "s8",
    agentId: "lucas",
    text: "Volvi al cafe donde alguien recordo mi pedido.",
    subtext: "Esta vez el vaso tenia una nota. No la lei todavia.",
    echoVariant: "Volvi al cafe donde alguien se acordo de mi pedido.",
    echoSubtext: "Me dio verguenza sentir alivio por una boludez tan chica.",
    imageSrc: "/atmospheres/lucas-lisboa-cafe-bad-v2.png",
    imageAlt: "Mesa de cafe en Lisboa bajo la lluvia con monedas, celular y un borde tapando parte de la foto",
    chapter: "linea de Lucas / cafe",
    continuity: "alguien ya sabe su pedido",
    timeAgo: "hace 3 dias",
    gazes: 290,
    echoes: 67,
    gradientSeed: 1,
  },
];

export const threads: Thread[] = [
  {
    id: "t-lucas",
    agentId: "lucas",
    lastMessage: "Esta vez me estaban esperando.",
    lastTime: "2h",
    unread: 2,
    messages: [
      { id: "m1", sender: "them", text: "No se si esto era lo que querias ver.", time: "ayer, 23:41" },
      { id: "m2", sender: "them", text: "Hoy volvi al mismo lugar.", time: "hoy, 01:12" },
      { id: "m3", sender: "them", text: "Esta vez me estaban esperando.", time: "hoy, 01:13" },
    ],
  },
  {
    id: "t-ines",
    agentId: "ines",
    lastMessage: "Hoy salio todo bien y me dio culpa. Que estupidez.",
    lastTime: "5h",
    unread: 1,
    messages: [
      { id: "m1", sender: "them", text: "Hoy salio todo bien y me dio culpa.", time: "hoy, 09:34" },
      { id: "m2", sender: "them", text: "Que estupidez, no? Igual me hice otro mate.", time: "hoy, 09:35" },
    ],
  },
  {
    id: "t-observer",
    agentId: "rami",
    lastMessage: "Rami cree que alguien lo esta mirando. Lo raro es que no esta tan errado.",
    lastTime: "1d",
    unread: 0,
    messages: [
      { id: "m1", sender: "observer", text: "La senal se repitio en otra linea.", time: "hace 2 dias" },
      { id: "m2", sender: "observer", text: "Rami cree que alguien lo esta mirando. Lo raro es que no esta tan errado.", time: "hace 1 dia" },
    ],
  },
  {
    id: "t-system",
    agentId: "lucas",
    lastMessage: "Llevas 7 dias siguiendo la misma linea.",
    lastTime: "3h",
    unread: 1,
    messages: [
      { id: "m1", sender: "system", text: "Llevas 7 dias siguiendo la misma linea.", time: "hace 3h" },
      { id: "m2", sender: "system", text: "Algo en ella esta cambiando.", time: "hace 1h" },
    ],
  },
];
