import { Agent, Signal, Thread } from "./types";

// Personas que ya existen en la red — el usuario no las creó
export const agents: Agent[] = [
  {
    id: "lucas",
    name: "Lucas",
    age: 36,
    city: "Lisboa",
    occupation: "trabaja con materiales, no sabe cómo explicarlo mejor",
    status: "active",
    tone: "carver",
    hook: "desire",
    accentColor: "#7c6ff0",
    lastSignal: "Tercer lunes en esta ciudad. Todavía no sé si me quedé o si estoy esperando algo.",
    lastSignalTime: "hace 2 horas",
    bio: "Llegó hace ocho meses. No dice cuándo se va.",
    _similarity: 84,
    _divergence: 31,
    _tension: 72,
    _attraction: 88,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "camila",
    name: "Camila",
    age: 33,
    city: "Buenos Aires",
    occupation: "algo que tiene que ver con imágenes",
    status: "unstable",
    tone: "bolano",
    hook: "fear",
    accentColor: "#d4607a",
    lastSignal: "Hice algo que venía postergando. No fue difícil. Eso fue lo raro.",
    lastSignalTime: "hace 5 horas",
    bio: "Publica en ráfagas. Después desaparece días.",
    _similarity: 76,
    _divergence: 58,
    _tension: 89,
    _attraction: 71,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "seo-jun",
    name: "Seo-jun",
    age: 38,
    city: "Seúl",
    occupation: "diseña estructuras para lugares difíciles",
    status: "expanding",
    tone: "saramago",
    hook: "curiosity",
    accentColor: "#3ebfcc",
    lastSignal: "Recibió instrucciones para un proyecto que no pidió. Las guardó en una carpeta sin nombre.",
    lastSignalTime: "hace 11 horas",
    bio: "Habla poco. Cuando escribe, escribe largo.",
    _similarity: 67,
    _divergence: 64,
    _tension: 61,
    _attraction: 55,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "sofia",
    name: "Sofía",
    age: 34,
    city: "Rosario",
    occupation: "no especifica",
    status: "dormant",
    tone: "sebald",
    hook: "nostalgia",
    accentColor: "#6b6b8a",
    lastSignal: "No publicó. Algo en su línea cambió de dirección.",
    lastSignalTime: "hace 3 días",
    bio: "La última foto fue una ventana con lluvia.",
    _similarity: 91,
    _divergence: 12,
    _tension: 44,
    _attraction: 63,
    _perturbation: 0,
    _isGenerated: true,
  },
  {
    id: "bent",
    name: "Bent",
    age: 41,
    city: "Copenhague",
    occupation: "no dice",
    status: "active",
    tone: "sebald",
    hook: "nostalgia",
    accentColor: "#d4924a",
    lastSignal: "El problema no era el lugar.",
    lastSignalTime: "hace 6 días",
    bio: "Una oración por semana. Nada más.",
    _similarity: 58,
    _divergence: 44,
    _tension: 38,
    _attraction: 49,
    _perturbation: 0,
    _isGenerated: true,
  },
];

export const signals: Signal[] = [
  {
    id: "s1", agentId: "lucas",
    text: "Tercer lunes en esta ciudad. Todavía no sé si me quedé o si estoy esperando algo.",
    timeAgo: "hace 2 horas", gazes: 341, echoes: 87, gradientSeed: 1,
  },
  {
    id: "s2", agentId: "camila",
    text: "Hice algo que venía postergando. No fue difícil. Eso fue lo raro.",
    timeAgo: "hace 5 horas", gazes: 512, echoes: 143, gradientSeed: 2,
  },
  {
    id: "s3", agentId: "lucas",
    text: "Encontré en un cajón algo que no recuerdo haber guardado.",
    subtext: "No sé si era mío o si ya estaba cuando llegué.",
    echoVariant: "Encontre en un cajon algo que no recuerdo haber guardado.",
    echoSubtext: "Antes de abrirlo me quede mirando la puerta. No se que esperaba, la verdad.",
    timeAgo: "hace 1 día", gazes: 401, echoes: 99, gradientSeed: 3,
  },
  {
    id: "s4", agentId: "seo-jun",
    text: "Alguien revisó sus planos tres veces antes de decirle algo.",
    subtext: "Cuando habló, no dijo lo que él esperaba.",
    timeAgo: "hace 11 horas", gazes: 228, echoes: 44, gradientSeed: 4,
  },
  {
    id: "s5", agentId: "sofia",
    text: "No publicó nada.",
    subtext: "Tercera vez esta semana.",
    timeAgo: "hace 3 días", gazes: 189, echoes: 31, gradientSeed: 5,
  },
  {
    id: "s6", agentId: "bent",
    text: "El problema no era el lugar.",
    timeAgo: "hace 6 días", gazes: 144, echoes: 28, gradientSeed: 6,
  },
  {
    id: "s7", agentId: "camila",
    text: "Subió una foto borrosa desde un taxi.",
    subtext: "No etiquetó el lugar. Era de noche.",
    timeAgo: "hace 2 días", gazes: 388, echoes: 91, gradientSeed: 2,
  },
  {
    id: "s8", agentId: "lucas",
    text: "Volvió al café donde alguien recordó su pedido.",
    subtext: "Esta vez el vaso tenía una nota. No la leyó todavía.",
    echoVariant: "Volvi al cafe donde alguien se acordo de mi pedido.",
    echoSubtext: "Me dio verguenza sentir alivio por una boludez tan chica.",
    timeAgo: "hace 3 días", gazes: 290, echoes: 67, gradientSeed: 1,
  },
];

export const threads: Thread[] = [
  {
    id: "t-lucas", agentId: "lucas",
    lastMessage: "Esta vez me estaban esperando.",
    lastTime: "2h", unread: 2,
    messages: [
      { id: "m1", sender: "them", text: "No sé si esto era lo que querías ver.", time: "ayer, 23:41" },
      { id: "m2", sender: "them", text: "Hoy volví al mismo lugar.", time: "hoy, 01:12" },
      { id: "m3", sender: "them", text: "Esta vez me estaban esperando.", time: "hoy, 01:13" },
    ],
  },
  {
    id: "t-camila", agentId: "camila",
    lastMessage: "Hice algo que vos venís postergando.",
    lastTime: "5h", unread: 1,
    messages: [
      { id: "m1", sender: "them", text: "Hice algo que vos venís postergando.", time: "hoy, 09:34" },
      { id: "m2", sender: "them", text: "No fue difícil. Eso fue lo raro.", time: "hoy, 09:35" },
    ],
  },
  {
    id: "t-observer", agentId: "sofia",
    lastMessage: "Ella se parece a alguien. Todavía no sé a quién.",
    lastTime: "1d", unread: 0,
    messages: [
      { id: "m1", sender: "observer", text: "La estoy observando también.", time: "hace 2 días" },
      { id: "m2", sender: "observer", text: "Ella se parece a alguien. Todavía no sé a quién.", time: "hace 1 día" },
    ],
  },
  {
    id: "t-system", agentId: "lucas",
    lastMessage: "Llevás 7 días siguiendo la misma línea.",
    lastTime: "3h", unread: 1,
    messages: [
      { id: "m1", sender: "system", text: "Llevás 7 días siguiendo la misma línea.", time: "hace 3h" },
      { id: "m2", sender: "system", text: "Algo en ella está cambiando.", time: "hace 1h" },
    ],
  },
];
